language: python
sudo: false
dist: xenial
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
before_script:
    - pip install -r requirements.txt
script:
    - python -c "import brutemap"
