language: python
dist: trusty
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
matrix:
  include:
    - dist: xenial
      python: "3.7"
    - dist: xenial
      python: "3.8-dev"
before_script:
    - pip install -r requirements.txt
script:
    - python -c "import brutemap"
